### ISSUE TITLE
Feature request: name conformence check on batch files

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#22]
This may not really be a feature request, but more of a workflow issue.

When a filename doesn't match the convention the script exits. This is good and right. 

But when processing a large batch of files, it can be a pain if 4 or 5 files out of 30 have a slight naming issues. 

Perhaps there is a way to when running this script of many directories to have it run the name check on all the files first so we know if there are some that need fixing?

**Comment by eddycolloton** [comment]
As of most recent commit, process_file.py will cycle through all provided directories and make a list of names, then check the complete list of names for invalid file names. If bad file names are found, all invalid names will be printed to terminal (and log) and then the script will exit. 

Should exit at the beginning if bad names are found, or otherwise will process all directories.
https://github.com/JPC-AV/JPC_AV_videoQC/commit/8742e606b6179ffbd55be748a642e770c2fa78a6
