### ISSUE TITLE
file path wrong

### ISSUE THREAD

**Issue by BleakleyMcD** [JPC-AV/JPC_AV_videoQC#6]
`/Users/medialab/github/jpc_av/JPC_AV_videoQC
≈:≈ python JPC_AV/process_file.py /Volumes/xUtility/JPC/DCvideo/JPC_AV_00001/JPC_AV_00001.mkv 
2024-01-08 17:47:10,523 - config.yaml sourced from /Users/medialab/github/jpc_av/config/config.yaml
Traceback (most recent call last):
  File "/Users/medialab/github/jpc_av/JPC_AV_videoQC/JPC_AV/process_file.py", line 11, in <module>
    from find_config import config_path
  File "/Users/medialab/github/jpc_av/JPC_AV_videoQC/JPC_AV/find_config.py", line 19, in <module>
    config_path = ConfigPath()
                  ^^^^^^^^^^^^
  File "/Users/medialab/github/jpc_av/JPC_AV_videoQC/JPC_AV/find_config.py", line 15, in __init__
    with open(self.config_yml) as f:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/medialab/github/jpc_av/config/config.yaml'`

**Comment by BleakleyMcD** [comment]
```
/Users/medialab/github/jpc_av/JPC_AV_videoQC
≈:≈ tree ~/github/jpc_av 
/Users/medialab/github/jpc_av
├── JPC_AV_ASpace
│   ├── README.md
│   ├── aspace-rename-directories.py
│   ├── authenticate.py
│   ├── creds_template.py
│   └── requirements.txt
└── JPC_AV_videoQC
    ├── JPC_AV
    │   ├── __pycache__
    │   │   ├── find_config.cpython-311.pyc
    │   │   └── log_setup.cpython-311.pyc
    │   ├── encoder_settings_check.py
    │   ├── exiftool_check.py
    │   ├── ffprobe_check.py
    │   ├── filename_check.py
    │   ├── find_config.py
    │   ├── log_setup.py
    │   ├── logs
    │   │   └── 2023-12-12
    │   │       └── 2023-12-12_19-28-21_JPC_AV_log.log
    │   ├── mediainfo_check.py
    │   └── process_file.py
    ├── README.md
    ├── config
    │   ├── JPC_AV_NTSC_MKV_2023-11-21.xml
    │   └── config.yaml
    ├── copyit.py
    ├── docs
    │   └── Roadmap.md
    ├── license
    │   └── LICENSE
    └── logs
        ├── 2024-01-08
        │   └── 2024-01-08_17-47-10_JPC_AV_log.log
        └── sample_JPC_AV_log.log

12 directories, 24 files
```

**Comment by eddycolloton** [comment]
The find_config script set the path to the config.yaml relative to the directory the script was called from (whoops!). So it was working for me because I was always running it from .../JPC_AV/JPC_AV_videoQC/JPC_AV/ 
But when you run it from .../JPC_AV/JPC_AV_videoQC/ everything was off by one level. 

find_config now operates relative to the location fo the _script_ and it doesn't can where the script is being run from.
This issue is resolved as of this commit: https://github.com/JPC-AV/JPC_AV_videoQC/commit/16ed3de11fb6cb9eef794a3cb5770fff99091a91
